name: IDX Morning Screener
on:
  schedule:
    - cron: '15 1 * * 1-5'   # 01:15 UTC = 08:15 WIB
  workflow_dispatch: {}
permissions:
  contents: read
concurrency:
  group: idx-screener
  cancel-in-progress: true
jobs:
  run-screener:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TZ: Asia/Jakarta
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run screener (.JK)
        run: python screener_idx_telegram.py
      - name: Notify failure to Telegram (optional)
        if: failure()
        run: |
          TEXT="❌ IDX Screener gagal pada $(date +'%Y-%m-%d %H:%M:%S %Z'). Cek logs di GitHub Actions."
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\":\"${TELEGRAM_CHAT_ID}\",\"text\":\"${TEXT}\"}"
